name: export-and-branch-solution
# Export solution from DEV environment
#  unpack it and prepare, commit and push a git branch with the changes

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  export-from-dev:
    runs-on: windows-latest
    env:
      RUNNER_DEBUG: 1

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true

    - name: who-am-i action
      uses: microsoft/powerplatform-actions/who-am-i@v0
      with:
        environment-url: 'https://org8afc7726.crm.dynamics.com/'
        user-name: 'admin@M365x639218.onmicrosoft.com'
        password-secret: ${{ secrets.password }}

    - name: export-solution action
      uses: microsoft/powerplatform-actions/export-solution@v0
      with:
        environment-url: 'https://org8afc7726.crm.dynamics.com/'
        user-name: 'admin@M365x639218.onmicrosoft.com'
        password-secret: ${{ secrets.password }}
        solution-name: DevOps1
        solution-output-file: out/exported/DevOps1.zip

    - name: unpack-solution action
      uses: microsoft/powerplatform-actions/unpack-solution@v0
      with:
        solution-file: out/exported/DevOps1.zip
        solution-folder: out/solutions/DevOps1
        solution-type: 'Unmanaged'
        overwrite-files: true

    - name: branch-solution, prepare it for a PullRequest
      uses: microsoft/powerplatform-actions/branch-solution@v0
      with:
        solution-folder: out/solutions/DevOps1
        solution-target-folder: solutions/DevOps1
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        allow-empty-commit: true
