name: export-and-branch-solution
# Export solution from DEV environment
#  unpack it and prepare, commit and push a git branch with the changes

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  export-from-dev:
    runs-on: windows-latest
    env:
      RUNNER_DEBUG: 1

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true

    - name: who-am-i action
      uses: microsoft/powerplatform-actions/who-am-i@v0.1.7
      with:
        environment-url: 'https://user9-dev.crm.dynamics.com/'
        user-name: 'user9@wrkdevops.onmicrosoft.com'
        password-secret: ${{ secrets.password }}

    - name: export-solution action
      uses: microsoft/powerplatform-actions/export-solution@v0.1.7
      with:
        environment-url: 'https://user9-dev.crm.dynamics.com/'
        user-name: 'user9@wrkdevops.onmicrosoft.com'
        password-secret: ${{ secrets.password }}
        solution-name: ALMLab
        solution-output-file: out/exported/ALMLab.zip

    - name: unpack-solution action
      uses: microsoft/powerplatform-actions/unpack-solution@v0.1.7
      with:
        solution-file: out/exported/ALMLab.zip
        solution-folder: out/solutions/ALMLab
        solution-type: 'Unmanaged'
        overwrite-files: true

    - name: branch-solution, prepare it for a PullRequest
      uses: microsoft/powerplatform-actions/branch-solution@v0.1.7
      with:
        solution-folder: out/solutions/ALMLab
        solution-target-folder: solutions/ALMLab
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        allow-empty-commit: true
