name: export-and-publish-solutionFile
# Export solution from DEV environment
#  unpack it and prepare, commit and push a git branch with the changes

on:
  repository_dispatch:

jobs:
  export-from-dev:
    runs-on: windows-latest
    env:
      RUNNER_DEBUG: 1

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true

    - name: who-am-i action
      uses: microsoft/powerplatform-actions/who-am-i@v0
      with:
        environment-url: 'https://alyousse.crm.dynamics.com/'
        user-name: 'alyousse@pfecrmonline.onmicrosoft.com'
        password-secret: ${{ secrets.password }}

    - name: export-solution action
      uses: microsoft/powerplatform-actions/export-solution@v0
      with:
        environment-url: 'https://alyousse.crm.dynamics.com/'
        user-name: 'alyousse@pfecrmonline.onmicrosoft.com'
        password-secret: ${{ secrets.password }}
        solution-name: GitHubDemo
        solution-output-file: out/exported/GitHubDemo.zip

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.2
      with:
        # Artifact name
        name: GitHubDemo.zip
        # A file, directory or wildcard pattern that describes what to upload
        path: out/exported
